on: [push, pull_request]

name: Continuous integration

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo update

  check:
    name: Check
    runs-on: ubuntu-latest
    needs: update
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    needs: update
    steps:
      - uses: actions/checkout@v3
      - name: Update apt
        run: sudo apt update
      - name: Install libudev
        run: sudo apt install libudev-dev
      - name: Install libxkbcommon
        run: sudo apt install libxkbcommon-dev
      - name: Install libwayland
        run: sudo apt install libwayland-dev
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    needs: update
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add clippy
      - run: cargo clippy -- -D warnings
